self-publish:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
    io.rancher.container.network: 'true'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.dns: 'true'
  image: brutus333/rancher-selfpublish
  stdin_open: true
  environment:
    BIGIP_ADDRESS: ${bigip_address}
    BIGIP_PARTITION: ${bigip_partition}
    BIGIP_ROUTEDOMAIN: ${bigip_routedomain}
    BIGIP_VIRTUALSERVER: ${bigip_virtualserver}
    BIGIP_POOL_PREFIX: ${bigip_pool_prefix}
    CONTAINER_DEFAULT_PORT: ${container_default_port}
load-balancer:
  ports:
  - ${load_balancer_port}
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.target.self-publish: self
  image: rancher/load-balancer-service
